// User
export enum USER_ACTIONS {
    SET_USER = "SET_USER",
}

export enum ALERT_ACTIONS {
    ADD_ALERT = "ADD_ALERT",
    REMOVE_ALERT = "REMOVE_ALERT",
}

export enum PROFILE_ACTIONS {
    SET_PROFILE = "SET_PROFILE",
    LOAD_PROFILE = "LOAD_PROFILE",
    REMOVE_PROFILE = "REMOVE_PROFILE",
}

export enum THEME_ACTIONS {
    SET_THEME = "SET_THEME",
}

export enum SITE_ACTIONS {
    SET_SITE = "SET_SITE",
}

export enum ORGANIZATION_ACTIONS {
    SET_ORGANIZATION = "SET_ORGANIZATION",
}

export enum POSITION_ACTIONS {
    SET_POSITION = "SET_POSITION",
}